config/routes.rb
Rails.application.routes.draw do
resources :movies
resources :lists do
resources :bookmarks
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :movie, uniqueness: { scope: :list }
  validates :list, uniqueness: { scope: :movie }
  validates :comment, length: { minimum: 6 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :bookmarks

  validates :content, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
before_action :set_list

  def new
    @bookmark = @list.bookmarks.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmarks = @list.bookmarks.new(bookmark_params)
    @bookmarks.save
    redirect_to lists_path(@list)

  end

  def destroy
    @bookmarks = Bookmark.find(params[:id])
    @bookmarks.destroy
    redirect_to lists_path(@list)
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @lists = List.find(params[:id])
  end

  def new
    @lists = List.new
  end

  def create
    @lists = List.new(lists_params)
    @lists.save
    redirect_to lists_path(@list)
  end

  private

  def set_list
    @lists = List.find(params[:id])
  end

  def lists_params
    params.require(:list).permit(:name)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.association :movie %>
  <%= f.button :submit, "Add Bookmark" %>
<% end %>

app/views/bookmarks/show.html.erb
<ul>
  <% @list.bookmarks.each do |bookmark| %>
    <li><%= bookmark.title %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1>Film lists</h1>
<ul>
  <% @lists.each do |list| %>
    <li><%= list.name %></li>
    <%= link_to "List details", list_path(list) %>

  <% end %>
</ul>

<%= link_to "Create a new list!", new_list_path%>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= simple_form_for(@lists) do |l| %>
  <%= l.input :name %>
  <%= l.submit %>
<% end %>

app/views/lists/show.html.erb
<h2><%= @lists.name %></h2>
<%= link_to "Back to your lists", lists_path(@lists) %>
<%= link_to "Add Film", new_list_bookmark_path(@lists) %>